from utils.helper import general_backbone
def prompt_for_kg(pdf_text):
      return (
    f"Based on the following text, create a nested JSON structure. "
    f"The structure should include a course with a title and its topics. "
    f"Each topic should have a title and a definition, where the definition contains more subtopics, "
    f"and each subtopic follows the same pattern with title and definition. If you find any relevant entity from this existing knowledge and the extracted text is part of that entity,please also add it as well e.g Photosynthesis is topic of Biology so subject would be Biology : Existing knowledge : {general_backbone()}"
    f"Please keep it as rule that title should not contain more than 3 words"
    f"I need detailed and descriptive json"
    f"The format should look like this:\n\n"
    f"{{\n"
    f"  \"subject\": \"{{subject_title}}\",\n"
    f"  \"topics\": [\n"
    f"    {{\n"
    f"      \"topic\": \"{{topic_title}}\",\n"
    f"      \"definition\": {{\n"
    f"        \"topics\": [\n"
    f"          {{\n"
    f"            \"title\": \"{{subtopic_title}}\",\n"
    f"            \"definition\": {{\n"
    f"              \"title\": \"{{subsubtopic_title}}\"\n"
    f"            }}\n"
    f"          }}\n"
    f"        ]\n"
    f"      }}\n"
    f"    }}\n"
    f"  ]\n"
    f"}}\n\n"
    f"{pdf_text}"
    )
